# Generated by Django 5.2 on 2025-05-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=0),
            preserve_default=False,
        ),
    ]
